spring:
  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: onboarding.taskmanagement.utils.dtos.in.UserRegisteredEventDto
        spring.json.trusted.packages: onboarding.taskmanagement.utils.dtos.in
        spring.json.use.type.headers: false

opensearch:
  host: http://localhost:9200
  username: admin
  password: T4skMgmt#2025!
  index:
    tasks: tasks-v1
    users: users-v1

server:
  port: 8080